export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just for You",
        description: 
            "Get interview questions and model answers based on your role, experience, and specic focus areas - no generic practice here."
    },
     {
        id: "02",
        title: "Learn at Your Own Pace",
        description: 
            "Expand answers only when you're ready, Dive deeper into nay concept instantly with AI-powered detailed explanations"
    },
     {
        id: "03",
        title: "Capture Your Insights",
        description: 
            "Add personal notes to any questions and pin important ones to the top - making your learning more organized and impactful."
    },
     {
        id: "04",
        title: 'Understand the "Why" Behind Answers',
        description: 
            "Beyond just answers - unlock detailed concepts explanations generated by AI, helping you truly master each topic."
    },
     {
        id: "05",
        title: "Save, Organize, and Revisit",
        description: 
            "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preperation right where you left off."
    },
]